name: Build

on:
    pull_request:
        types: [opened, reopened, edited, synchronize, ready_for_review]

jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
        - name: Check out code
          uses: actions/checkout@v4
        - name: Compile Visual Studio Project with MSBuild for x86
          shell: cmd 
          run: ${{ '"C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild FelsokningExt.vcxproj /p:configuration=release /p:platform=x86' }}
          working-directory: ${{ github.workspace }}\FelsokningExt
        - name: Compile Visual Studio Project with MSBuild for x64
          shell: cmd 
          run: ${{ '"C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild FelsokningExt.vcxproj /p:configuration=release /p:platform=x64' }}
          working-directory: ${{ github.workspace }}\FelsokningExt
        - name: Install ProcDump
          shell: pwsh
          run: Invoke-RestMethod -Uri "https://download.sysinternals.com/files/Procdump.zip" -OutFile Procdump.zip; Expand-Archive -Path ./Procdump.zip;
        - name: List Processes (Will Be Removed)
          shell: pwsh
          run: Get-Process | Format-Table -Autosize
        - name: Dump PowerShell Process
          shell: cmd
          run: .\Procdump\procdump64.exe -accepteula -ma -n 1 -r pwsh
        - name: Run CDB With Debugger Extension Loaded
          shell: cmd
          run: cdb -z pwsh.DMP -a ${{ github.workspace }}\FelsokningExt\x64\release\FelsokningExt.dll -c "!deep 5;qd"